# Generated by Django 2.2.2 on 2019-09-04 10:20

import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("fao_case_list", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255, verbose_name="URL")),
                (
                    "metadata",
                    jsonfield.fields.JSONField(
                        dump_kwargs={
                            "cls": jsonfield.encoder.JSONEncoder,
                            "separators": (",", ":"),
                        },
                        load_kwargs={},
                        verbose_name="Metadaten",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisierung"),
                ),
            ],
            options={"verbose_name": "Feed", "verbose_name_plural": "Feeds"},
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.CharField(max_length=255, null=True, verbose_name="GUID"),
                ),
                (
                    "data",
                    jsonfield.fields.JSONField(
                        dump_kwargs={
                            "cls": jsonfield.encoder.JSONEncoder,
                            "separators": (",", ":"),
                        },
                        load_kwargs={},
                        verbose_name="Daten",
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Gelesen"
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fao_case_list.Feed",
                        verbose_name="Feed",
                    ),
                ),
            ],
            options={"verbose_name": "Eintrag", "verbose_name_plural": "Einträge"},
        ),
    ]
