# Generated by Django 2.2.8 on 2020-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fao_case_list", "0003_feed_bgh"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="short_name",
            field=models.CharField(
                default="X", max_length=255, verbose_name="Kurzbezeichnung"
            ),
            preserve_default=False,
        ),
    ]
